version: 2

jobs:

  build_image: &build_image
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            make $PLATFORM

  php_56:
    <<: *build_image
    environment:
      - PLATFORM: php-5.6

  php_70:
    <<: *build_image
    environment:
      - PLATFORM: php-7.0

  php_71:
    <<: *build_image
    environment:
      - PLATFORM: php-7.1

  php_7x:
    <<: *build_image
    environment:
      - PLATFORM: php-7.x

  solr:
    <<: *build_image
    environment:
      - PLATFORM: solr

  apache2:
    <<: *build_image
    environment:
      - PLATFORM: apache2

  oauth2:
    <<: *build_image
    environment:
      - PLATFORM: oauth2

workflows:
  version: 2
  build:
    jobs:
      - php_56
      - php_70
      - php_71
      - php_7x
      - solr
      - apache2
      - oauth2
